[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.3.0",
<<<<<<< HEAD
    "flask-wtf>=1.2.2",
=======
    "flask-mail>=0.10.0",
>>>>>>> ded7f2e4447248a018f7dd7d09de9c43eb09fa0d
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.10",
    "wtforms>=3.2.1",
<<<<<<< HEAD
    "stripe>=12.4.0",
    "werkzeug>=3.1.3",
    "sqlalchemy>=2.0.43",
    "flask-login>=0.6.3",
    "flask-mail>=0.10.0",
=======
    "sqlalchemy>=2.0.43",
    "werkzeug>=3.1.3",
    "flask-login>=0.6.3",
    "flask-wtf>=1.2.2",
    "stripe>=12.4.0",
    "python-dotenv>=1.1.1",
    "pyjwt>=2.10.1",
    "flask-dance>=7.1.0",
    "oauthlib>=3.3.1",
    "sendgrid>=6.12.4",
    "openai>=1.102.0",
    "twilio>=9.7.1",
    "notion-client>=2.5.0",
    "trafilatura>=2.0.0",
    "apscheduler>=3.11.0",
    "redis>=6.4.0",
    "celery>=5.5.3",
    "flask-caching>=2.3.1",
    "flask-limiter>=3.12",
    "python-dateutil>=2.9.0.post0",
    "schedule>=1.2.2",
>>>>>>> ded7f2e4447248a018f7dd7d09de9c43eb09fa0d
]
